steps:
- name: 'gcr.io/cloud-builders/dotnet'
  args: ['publish', '-c', 'Release', '-o', 'out']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', 'app.yaml']

# Additional steps can be added as needed for your specific build and deployment process.
